"""Add expense model and user relationship

Revision ID: fdd60a6ec253
Revises: 0002
Create Date: 2025-10-25 13:45:59.269013

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore  # pylint: disable=import-error

# revision identifiers, used by Alembic.
revision: str = "fdd60a6ec253"
down_revision: Union[str, Sequence[str], None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fk_user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "LEBENSMITTEL",
                "LIEFERSERVICE",
                "DROGERIEARTIKEL",
                "URLAUB",
                "KLEIDUNG",
                "OTHER",
                name="expensecategory",
            ),
            nullable=False,
        ),
        sa.Column("expensedate", sa.DateTime(timezone=True), nullable=False),
        sa.Column("vendor", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["fk_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_expenses_id"), "expenses", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expenses_id"), table_name="expenses")
    op.drop_table("expenses")
    # ### end Alembic commands ###
